#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  7 09:48:36 2019

@author: sc2195
"""
from pyscf import gto
from pyscf import dft
from pyscf import lib
from pyscf import df
from pyscf.geomopt import berny_solver
from pyscf.tools import cubegen
import numpy as np
from os import listdir
from os.path import isfile, join

def getAtomCoordsfromPDB(file):
    with open(file) as f:
        lineList = f.readlines()
        data = [item for item in lineList if item[:6] == 'HETATM']
        atom_coords = ''
        for n in data:
            atom_coords += '     '+n.strip()[12:14]
            atom_coords += n.strip()[27:38]+','
            atom_coords += n.strip()[38:46]+','
            atom_coords += n.strip()[46:54]+';\n'
            
        return(atom_coords)
        

onlyfiles = [f for f in listdir('nicola') if isfile(join('nicola', f))]
files = [i for i in onlyfiles if '.pdb' in i]
print(getAtomCoordsfromPDB('nicola/'+files[0]))